#imports
from selenium import webdriver
from selenium.webdriver.common.keys import Keys  
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
import time
from random import randint

#invoking chromedriver
chromedriver = "/home/ajeya/steam/testing/chromedriver"
driver = webdriver.Chrome(chromedriver)

actions = ActionChains(driver)

#Test1 - Check if clicking on a game of home page works
def test1():
	driver.get("http://localhost:4200/")
	driver.maximize_window()
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	driver.find_element_by_id("img1").click()
	time.sleep(2)
	driver.execute_script("window.history.go(-1)")
	time.sleep(6)
	print("Test 1 passed succesfully")
	
#Test2 - Checking if next and previous toggle buttons work, and all the images in the slideshow work properly.
def test2():
	driver.get("http://localhost:4200/")
	driver.maximize_window()
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	driver.find_element_by_id("prev").click()
	time.sleep(2)
	driver.find_element_by_id("next").click()
	time.sleep(2)
	driver.find_element_by_id("img1").click()
	time.sleep(2)
	driver.execute_script("window.history.go(-1)")
	time.sleep(2)
	driver.find_element_by_id("next").click()
	time.sleep(2)
	driver.find_element_by_id("img2").click()
	time.sleep(6)
	print("Test 2 passed succesfully")

#Test3 - Checking if all game catalog button works
def test3():
	driver.get("http://localhost:4200/")
	driver.maximize_window()
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	l=driver.find_elements_by_xpath("//*[contains(text(), 'all games')]")
	l[0].click()
	time.sleep(6)
	print("Test 3 passed succesfully")

#Test4 - Checking if sidebar functionality works
def test4():
	driver.get("http://localhost:4200/")
	driver.maximize_window()
	time.sleep(2)
	driver.find_element_by_id("sidebar-toggle-2").click()
	time.sleep(2)
	l=driver.find_elements_by_tag_name("li")
	r=randint(0,4)
	l[r].click()
	time.sleep(2)
	driver.execute_script("window.history.go(-1)")
	time.sleep(6)
	print("Test 4 passed succesfully")


#Test5 - Checking if the Aqua button athe top takes user to the home page
def test5():
	driver.get("http://localhost:4200/")
	driver.maximize_window()
	time.sleep(2)
	time.sleep(2)
	driver.find_element_by_id("sidebar-toggle-2").click()
	time.sleep(2)
	l=driver.find_elements_by_tag_name("li")
	r=randint(0,4)
	l[r].click()
	time.sleep(2)
	l1=driver.find_elements_by_xpath("//*[contains(text(), 'AQUA')]")
	l1[0].click()
	time.sleep(6)
	print("Test 5 passed succesfully")

#Test6 - Checking if multistage download section works, that is, checking if all games are loaded when load more button is clicked
def test6():
	driver.get("http://localhost:4200/")
	driver.maximize_window()
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	l=driver.find_elements_by_xpath("//*[contains(text(), 'all games')]")
	l[0].click()
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	l1=driver.find_elements_by_xpath("//*[contains(text(), 'more')]")
	l1[0].click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight/2)")
	time.sleep(2)
	driver.execute_script("window.scrollTo(document.body.scrollHeight/2,document.body.scrollHeight)")
	time.sleep(6)
	print("Test 6 passed succesfully")

#Test7 - Checking if a game gets added to the cart
def test7():
	driver.get("http://localhost:4200/")
	driver.maximize_window()
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	driver.find_element_by_id("img1").click()
	time.sleep(2)
	l1=driver.find_elements_by_xpath("//*[contains(text(), 'Buy')]")
	l1[0].click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(3)
	driver.execute_script("window.scrollTo(document.body.scrollHeight,0)")
	time.sleep(2)
	driver.find_element_by_id("sidebar-toggle-2").click()
	time.sleep(2)
	l=driver.find_elements_by_tag_name("li")
	l[2].click()
	time.sleep(6)
	print("Test 7 passed succesfully")

#Test8 - Checking if a game gets deleted from a cart
def test8():
	driver.get("http://localhost:4200/")
	driver.maximize_window()
	time.sleep(2)
	driver.find_element_by_id("sidebar-toggle-2").click()
	time.sleep(2)
	l=driver.find_elements_by_tag_name("li")
	l[2].click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	driver.execute_script("window.scrollTo(document.body.scrollHeight,0)")
	time.sleep(2)
	l1=driver.find_elements_by_xpath("//*[contains(text(), 'Delete')]")
	l1[0].click()
	time.sleep(2)
	obj = driver.switch_to.alert
	obj.accept()
	time.sleep(6)
	print("Test 8 passed succesfully")


#Test9 - Checking if checkout happens
def test9():
	driver.get("http://localhost:4200/")
	driver.maximize_window()
	driver.find_element_by_id("sidebar-toggle-2").click()
	time.sleep(2)
	l=driver.find_elements_by_tag_name("li")
	l[1].click()
	time.sleep(2)
	l2=driver.find_elements_by_id("game")
	l2[0].click()
	time.sleep(2)
	l3=driver.find_elements_by_xpath("//*[contains(text(), 'Buy')]")
	l3[0].click()
	time.sleep(2)
	driver.execute_script("window.history.go(-1)")
	time.sleep(2)
	l2=driver.find_elements_by_id("game")
	l2[1].click()
	time.sleep(2)
	l3=driver.find_elements_by_xpath("//*[contains(text(), 'Buy')]")
	l3[0].click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(document.body.scrollHeight,0)")
	driver.find_element_by_id("sidebar-toggle-2").click()
	l[2].click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	driver.find_element_by_id("un").send_keys("Ajeya")
	time.sleep(2)
	driver.find_element_by_id("em").send_keys("ajeyabs@gmail.com")
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	l4=driver.find_elements_by_xpath("//*[contains(text(), 'Checkout')]")
	m=l4[0]
	actions.click(m)
	actions.perform()
	time.sleep(2)
	obj = driver.switch_to.alert
	obj.accept()
	time.sleep(6)
	print("Test 9 passed succesfully")

#Test10 - Checking what happens when one of the fields is not mentioned before checkout
def test10():
	driver.get("http://localhost:4200/")
	driver.maximize_window()
	driver.find_element_by_id("sidebar-toggle-2").click()
	time.sleep(2)
	l=driver.find_elements_by_tag_name("li")
	l[1].click()
	time.sleep(2)
	l2=driver.find_elements_by_id("game")
	l2[0].click()
	time.sleep(2)
	l3=driver.find_elements_by_xpath("//*[contains(text(), 'Buy')]")
	l3[0].click()
	time.sleep(2)
	driver.execute_script("window.history.go(-1)")
	time.sleep(2)
	l2=driver.find_elements_by_id("game")
	l2[1].click()
	time.sleep(2)
	l3=driver.find_elements_by_xpath("//*[contains(text(), 'Buy')]")
	l3[0].click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(document.body.scrollHeight,0)")
	driver.find_element_by_id("sidebar-toggle-2").click()
	l[2].click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	driver.find_element_by_id("un").send_keys("Ajeya")
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	l4=driver.find_elements_by_xpath("//*[contains(text(), 'Checkout')]")
	l4[0].click()
	time.sleep(2)
	obj = driver.switch_to.alert
	obj.accept()
	time.sleep(6)
	print("Test 10 passed succesfully")

#Test11 - Checking if contactus form works
def test11():
	driver.get("http://localhost:4200/")
	driver.maximize_window()
	driver.find_element_by_id("sidebar-toggle-2").click()
	time.sleep(2)
	l=driver.find_elements_by_tag_name("li")
	l[3].click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	driver.find_element_by_id("fn").send_keys("Ajeya")
	time.sleep(2)
	driver.find_element_by_id("fe").send_keys("ajeyabs@gmail.com")
	time.sleep(2)
	driver.find_element_by_id("fr").send_keys("This website is good!")
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	l4=driver.find_elements_by_xpath("//*[contains(text(), 'Submit')]")
	l4[0].click()
	time.sleep(6)
	print("Test 11 passed successfully")

#Test12 - Checking what happens if contactus form is not filled completely
def test12():
	driver.get("http://localhost:4200/")
	driver.maximize_window()
	driver.find_element_by_id("sidebar-toggle-2").click()
	time.sleep(2)
	l=driver.find_elements_by_tag_name("li")
	l[3].click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	driver.find_element_by_id("fn").send_keys("Ajeya")
	time.sleep(2)
	driver.find_element_by_id("fe").send_keys("ajeyabs@gmail.com")
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	l4=driver.find_elements_by_xpath("//*[contains(text(), 'Submit')]")
	l4[0].click()
	time.sleep(2)
	obj = driver.switch_to.alert
	obj.accept()
	time.sleep(6)
	print("Test 12 passed successfully")


#Test13 - Checking if the statistics graphs are proper
def test13():
	driver.get("http://localhost:4200/")
	
	driver.maximize_window()
	driver.find_element_by_id("sidebar-toggle-2").click()
	time.sleep(2)
	l=driver.find_elements_by_tag_name("li")
	l[4].click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	driver.find_element_by_xpath("//*[contains(text(), 'per year')]").click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	driver.find_element_by_xpath("//*[contains(text(), 'Date')]").click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	l4=driver.find_elements_by_xpath("//*[contains(text(), 'per platform')]")
	l4[1].click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	driver.find_element_by_xpath("//*[contains(text(), 'Developer')]").click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	driver.find_element_by_xpath("//*[contains(text(), 'per genre')]").click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(6)
	print("Test 13 passed successfully")

#Test14 - Checking what happens when request for a new graph is asked
def test14():
	driver.get("http://localhost:4200/")
	driver.maximize_window()
	ab=driver.find_element_by_id("sidebar-toggle-2")
	driver.implicitly_wait(2)
	ActionChains(driver).move_to_element(ab).click(ab).perform()
	time.sleep(2)
	l=driver.find_elements_by_tag_name("li")
	l[4].click()
	time.sleep(2)	
	driver.find_element_by_xpath("//*[contains(text(), 'Request')]").click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	driver.find_element_by_id("p1").send_keys("Ratings")
	time.sleep(2)
	driver.find_element_by_id("p2").send_keys("Achievements")
	time.sleep(2)
	driver.find_element_by_id("req").click()
	time.sleep(2)
	driver.find_element_by_id("p1").send_keys("Ratings")
	time.sleep(2)
	driver.find_element_by_id("p2").send_keys("Achievements")
	time.sleep(2)
	driver.find_element_by_id("req").click()
	time.sleep(6)
	print("Test 14 passed successfully")

#Test15 - Checking what happens when request for a new graph is incompletely filled
def test15():
	driver.get("http://localhost:4200/")
	driver.maximize_window()
	ab=driver.find_element_by_id("sidebar-toggle-2")
	driver.implicitly_wait(2)
	ActionChains(driver).move_to_element(ab).click(ab).perform()
	time.sleep(2)
	l=driver.find_elements_by_tag_name("li")
	l[4].click()
	time.sleep(2)	
	driver.find_element_by_xpath("//*[contains(text(), 'Request')]").click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(2)
	driver.find_element_by_id("p1").send_keys("Ratings")
	time.sleep(2)
	driver.find_element_by_id("req").click()
	time.sleep(2)
	obj = driver.switch_to.alert
	obj.accept()
	time.sleep(2)
	driver.find_element_by_id("p2").send_keys("Playtime")
	time.sleep(2)
	driver.find_element_by_id("req").click()
	time.sleep(2)
	driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
	time.sleep(6)
	print("Test 15 passed successfully")

#test1()
#test2()
#test3()
#test4()
#test5()
#test6()
#test7()
#test8()
#test9()
#test10()
test11()
test12()
test13()
test14()
test15()
